export const firstName = {
  a: "Captain",
  b: "Wonder",
  c: "Super",
  d: "Phantom",
  e: "Dark",
  f: "Incredible",
  g: "Professor",
  h: "Iron",
  i: "Hawk",
  j: "Archer",
  k: "Steel",
  l: "Bolt",
  m: "Atomic",
  n: "Torch",
  o: "Space",
  p: "Mega",
  q: "Turbo",
  r: "Fantastic",
  s: "Invisible",
  t: "Night",
  u: "Silver",
  v: "Aqua",
  w: "Amazing",
  x: "Giant",
  y: "Rock",
  z: "Ghost",
};

export const lastName = {
  January: "Shield",
  February: "Arrow",
  March: "Justice",
  April: "Thunder",
  May: "Rider",
  June: "Falcon",
  July: "Ninja",
  August: "Spider",
  September: "Beast",
  October: "Blade",
  November: "Hulk",
  December: "Doom",
};
